import { readFileSync, writeFileSync } from 'node:fs';
const core = readFileSync(new URL('./pip.js', import.meta.url), 'utf8').replaceAll('export ', '');
const ui = readFileSync(new URL('./player-button.js', import.meta.url), 'utf8');
writeFileSync(new URL('./content.js', import.meta.url), '// Generated by node build.js. Edit pip.js and player-button.js.\n' + core + '\n' + ui);
